### PR TITLE
Add a function to create markdown file

### PR DESCRIPTION
**Pull request by yfgeek**
Add a function to create markdown file

支持Markdown文件的输出

支持单个文件输出

支持图片文件保存到本地

### CODE REVIEW

**Comment by cheezer** [comment]
Thanks! But I encountered an error when retrieving images. 

Downloading
Traceback (most recent call last):
  File "Crawler.py", line 153, in <module>
    output2md()
  File "Crawler.py", line 130, in output2md
    data = urllib.urlretrieve(img['src'],path)
  File "/home/michaelxie/tools/anaconda2/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/home/michaelxie/tools/anaconda2/lib/python2.7/urllib.py", line 249, in retrieve
    tfp = open(filename, 'wb')
IOError: [Errno 2] No such file or directory: 'images/d97999efbebc24fbe64b411028f56f4c.jpg'

**Comment by yfgeek** [comment]
You should create the folder named "images".
And I've fixed the download bugs I will pull the new one to you

**Comment by yfgeek** [comment]
Thanks for contributing to this awesome code to Github ,and then I've download Baidu space blogs yesterday.

Good work!

Here is my old blogs:

https://github.com/yfgeek/Blog

**Comment by yfgeek** [comment]
I‘ve fixed the bugs.

**Comment by cheezer** [comment]
Thanks!

**Pull request merged**
